FROM node:16

ADD package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin

RUN npm install
RUN npm install -g serve
RUN npm run build

WORKDIR /fmdeploy
ADD . /fmdeploy

EXPOSE 3000

CMD ["serve ", "-s", "build"]