version: "2"

services:
  backend:
    user: root
    build:
      context: backend
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
      - ./database:/database.db
      - ./inputfiles:/inputfiles
      - ./modelfiles:/modelfiles
      - ./outputfiles:/outputfiles
    labels:
      - traefik.enable=true
      - traefik.http.routers.fmdeploybackendrouter.rule=Host(`fmdeploy-api.localhost`)
      - traefik.http.services.backend.loadbalancer.server.port=8000

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    expose:
      - 3000
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/app/node_modules:cached
    labels:
      - traefik.enable=true
      - traefik.http.routers.fmdeployfrontendrouter.rule=Host(`fmdeploy.localhost`)
      - traefik.http.services.frontend.loadbalancer.server.port=3000

  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - ./traefik.dev.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro
