version: '2'

services:

  db:
    container_name: db
    build: ./backend/docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: fmdeploy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 2f2kir2y49xy6g 
      MYSQL_ROOT_PASSWORD: 2f2kir2y49xy6g 
    ports:
      - "3307:3306"
    volumes:
      - ./backend/docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./backend/docker/mysql/conf.d:/etc/mysql/conf.d
      - ./backend/log/mysql:/var/log/mysql 
      - persist-mysql:/var/lib/mysql
    networks:
      - local-net

  api:
    links:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: api
    ports:  
      - "36554:8000"
    volumes:
      - ./backend:/app/:cached
      - ./database:/database.db
      - ./inputfiles:/inputfiles
      - ./modelfiles:/modelfiles
      - ./outputfiles:/outputfiles
    networks:
      - local-net

  frontend:
    depends_on:
        - api
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
          - URI=http://localhost:36554
    container_name: client
    ports:  
      - "36555:3000"
    volumes:
      - ./frontend:/app:cached
      - ./frontend/node_modules:/app/node_modules:cached

networks:
  local-net:
    driver: bridge

volumes:
  persist-mysql:
