version: '2'

services:

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - --log.level=ERROR
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=namedotcom
      - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.email=marcelodefreitas25@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - NAMECOM_USERNAME=marcelodefreitas
      - NAMECOM_API_TOKEN=9c22fecbcf9762e6aba891832dc2b39c7fff4747
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    container_name: db
    build: ./backend/docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: fmdeploy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 2f2kir2y49xy6g 
      MYSQL_ROOT_PASSWORD: 2f2kir2y49xy6g 
    volumes:
      - ./backend/docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./backend/docker/mysql/conf.d:/etc/mysql/conf.d
      - ./backend/log/mysql:/var/log/mysql 
      - persist-mysql:/var/lib/mysql
    networks:
      - local-net
        
  backend:
    links:
      - db
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
      - ./inputfiles:/inputfiles
      - ./modelfiles:/modelfiles
      - ./outputfiles:/outputfiles
    networks:
      - local-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`test3.fmdeploy.live`)
      - traefik.http.routers.backend.service=backend
      - traefik.http.services.backend.loadbalancer.server.port=8000
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
    


networks:
  local-net:
    driver: bridge

volumes:
  persist-mysql: