version: '3.8'

services:

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    expose:  
      - 80
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    expose:  
      - 3000
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development
