FROM python:3.7.7

WORKDIR /fmdeploy

COPY ./requirements.txt /fmdeploy/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /fmdeploy/requirements.txt

COPY ./app /fmdeploy/app

EXPOSE 8000

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornH11Worker", "app.main:app", "-b 0.0.0.0:8000"]