FROM python:3.7.7

WORKDIR /fmdeploy

RUN pip install --upgrade pip

COPY ./requirements.txt /fmdeploy/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /fmdeploy/requirements.txt

COPY ./app /fmdeploy/app

RUN apt-get update -y && apt-get install -y --no-install-recommends build-essential gcc \libsndfile1 
RUN apt-get -y install libsndfile1
RUN apt-get -y install ffmpeg

EXPOSE 8000
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornH11Worker", "app.main:app", "-b 0.0.0.0:8000"]